/* Palánta – Tudástár bővítés (bővíthető)
   Mezők: k (egyedi kulcs), n (magyar név), lat (latin), c (kategória), a (gondozási archetípus).
   A részletes gondozást az archetípus adja (index.html → CARE_ARCHETYPES); egyedi mezőkkel felülírható (pl. tox:1, light:'low').
   Kategóriák: flower, veg, fruit, herb, house, succ, fern, palm, orn (dísznövény). */
window.PLANT_DB_EXTRA = [
  /* ───────── VIRÁGOK ───────── */
  { k: 'daffodil', n: 'Nárcisz', lat: 'Narcissus', c: 'flower', a: 'bulb_flower', tox: 1 },
  { k: 'hyacinth', n: 'Jácint', lat: 'Hyacinthus orientalis', c: 'flower', a: 'bulb_flower', tox: 1 },
  { k: 'crocus', n: 'Krókusz', lat: 'Crocus', c: 'flower', a: 'bulb_flower' },
  { k: 'snowdrop', n: 'Hóvirág', lat: 'Galanthus nivalis', c: 'flower', a: 'bulb_flower', tox: 1 },
  { k: 'muscari', n: 'Gyöngyike', lat: 'Muscari', c: 'flower', a: 'bulb_flower' },
  { k: 'allium_orn', n: 'Dísz fokhagyma', lat: 'Allium', c: 'flower', a: 'bulb_flower' },
  { k: 'lily', n: 'Liliom', lat: 'Lilium', c: 'flower', a: 'bulb_flower', tox: 1 },
  { k: 'gladiolus', n: 'Kardvirág', lat: 'Gladiolus', c: 'flower', a: 'bulb_flower' },
  { k: 'freesia', n: 'Frézia', lat: 'Freesia', c: 'flower', a: 'bulb_flower' },
  { k: 'amaryllis', n: 'Amarillisz', lat: 'Hippeastrum', c: 'flower', a: 'bulb_flower', tox: 1 },
  { k: 'ranunculus', n: 'Kerti boglárka', lat: 'Ranunculus asiaticus', c: 'flower', a: 'bulb_flower', tox: 1 },
  { k: 'anemone', n: 'Szellőrózsa', lat: 'Anemone', c: 'flower', a: 'perennial_flower', tox: 1 },
  { k: 'dahlia', n: 'Dália', lat: 'Dahlia', c: 'flower', a: 'perennial_flower' },
  { k: 'canna', n: 'Kanna', lat: 'Canna', c: 'flower', a: 'perennial_flower' },
  { k: 'daylily', n: 'Sásliliom', lat: 'Hemerocallis', c: 'flower', a: 'perennial_flower' },
  { k: 'iris', n: 'Nőszirom', lat: 'Iris', c: 'flower', a: 'perennial_flower', tox: 1 },
  { k: 'peony', n: 'Bazsarózsa', lat: 'Paeonia', c: 'flower', a: 'perennial_flower' },
  { k: 'dianthus', n: 'Szegfű', lat: 'Dianthus', c: 'flower', a: 'perennial_flower' },
  { k: 'aster', n: 'Őszirózsa', lat: 'Aster', c: 'flower', a: 'perennial_flower' },
  { k: 'echinacea', n: 'Bíbor kasvirág', lat: 'Echinacea purpurea', c: 'flower', a: 'perennial_flower' },
  { k: 'rudbeckia', n: 'Kúpvirág', lat: 'Rudbeckia', c: 'flower', a: 'perennial_flower' },
  { k: 'coreopsis', n: 'Menyecskeszem', lat: 'Coreopsis', c: 'flower', a: 'perennial_flower' },
  { k: 'gaillardia', n: 'Kokárdavirág', lat: 'Gaillardia', c: 'flower', a: 'perennial_flower' },
  { k: 'shasta', n: 'Margaréta', lat: 'Leucanthemum', c: 'flower', a: 'perennial_flower' },
  { k: 'delphinium', n: 'Szarkaláb', lat: 'Delphinium', c: 'flower', a: 'perennial_flower', tox: 1 },
  { k: 'lupine', n: 'Csillagfürt', lat: 'Lupinus', c: 'flower', a: 'perennial_flower', tox: 1 },
  { k: 'foxglove', n: 'Gyűszűvirág', lat: 'Digitalis purpurea', c: 'flower', a: 'perennial_flower', tox: 1, diff: 'med' },
  { k: 'hollyhock', n: 'Mályvarózsa', lat: 'Alcea rosea', c: 'flower', a: 'perennial_flower' },
  { k: 'bellflower', n: 'Harangvirág', lat: 'Campanula', c: 'flower', a: 'perennial_flower' },
  { k: 'primrose', n: 'Kankalin', lat: 'Primula', c: 'flower', a: 'perennial_flower' },
  { k: 'phlox', n: 'Lángvirág', lat: 'Phlox', c: 'flower', a: 'perennial_flower' },
  { k: 'salvia_perennial', n: 'Évelő zsálya', lat: 'Salvia nemorosa', c: 'flower', a: 'perennial_flower' },
  { k: 'sunflower', n: 'Napraforgó', lat: 'Helianthus annuus', c: 'flower', a: 'annual_flower' },
  { k: 'marigold', n: 'Büdöske', lat: 'Tagetes', c: 'flower', a: 'annual_flower' },
  { k: 'zinnia', n: 'Rézvirág', lat: 'Zinnia elegans', c: 'flower', a: 'annual_flower' },
  { k: 'cosmos', n: 'Pillangóvirág', lat: 'Cosmos', c: 'flower', a: 'annual_flower' },
  { k: 'snapdragon', n: 'Oroszlánszáj', lat: 'Antirrhinum majus', c: 'flower', a: 'annual_flower' },
  { k: 'pansy', n: 'Árvácska', lat: 'Viola × wittrockiana', c: 'flower', a: 'annual_flower' },
  { k: 'viola', n: 'Ibolya', lat: 'Viola', c: 'flower', a: 'perennial_flower' },
  { k: 'nasturtium', n: 'Sarkantyúka', lat: 'Tropaeolum majus', c: 'flower', a: 'annual_flower' },
  { k: 'impatiens', n: 'Nebáncsvirág', lat: 'Impatiens walleriana', c: 'flower', a: 'annual_flower' },
  { k: 'begonia_bedding', n: 'Kerti begónia', lat: 'Begonia semperflorens', c: 'flower', a: 'annual_flower' },
  { k: 'lobelia', n: 'Lobélia', lat: 'Lobelia erinus', c: 'flower', a: 'annual_flower' },
  { k: 'alyssum', n: 'Ternye', lat: 'Lobularia maritima', c: 'flower', a: 'annual_flower' },
  { k: 'verbena', n: 'Verbéna', lat: 'Verbena', c: 'flower', a: 'annual_flower' },
  { k: 'celosia', n: 'Kakastaréj', lat: 'Celosia', c: 'flower', a: 'annual_flower' },
  { k: 'ageratum', n: 'Májvirág', lat: 'Ageratum houstonianum', c: 'flower', a: 'annual_flower' },
  { k: 'calendula', n: 'Körömvirág', lat: 'Calendula officinalis', c: 'flower', a: 'annual_flower' },
  { k: 'gazania', n: 'Gazánia', lat: 'Gazania', c: 'flower', a: 'annual_flower' },
  { k: 'osteospermum', n: 'Kapföldi margaréta', lat: 'Osteospermum', c: 'flower', a: 'annual_flower' },
  { k: 'nemesia', n: 'Nemézia', lat: 'Nemesia', c: 'flower', a: 'annual_flower' },
  { k: 'petunia_surfinia', n: 'Szörfínia', lat: 'Petunia (Surfinia)', c: 'flower', a: 'annual_flower' },
  { k: 'poppy', n: 'Pipacs', lat: 'Papaver', c: 'flower', a: 'annual_flower', tox: 1 },
  { k: 'cornflower', n: 'Búzavirág', lat: 'Centaurea cyanus', c: 'flower', a: 'annual_flower' },
  { k: 'forgetmenot', n: 'Nefelejcs', lat: 'Myosotis', c: 'flower', a: 'annual_flower' },
  { k: 'sweetpea', n: 'Szagosbükköny', lat: 'Lathyrus odoratus', c: 'flower', a: 'climber', tox: 1 },
  { k: 'morningglory', n: 'Hajnalka', lat: 'Ipomoea', c: 'flower', a: 'climber', tox: 1 },
  { k: 'begonia_tuberous', n: 'Gumós begónia', lat: 'Begonia × tuberhybrida', c: 'flower', a: 'perennial_flower' },
  { k: 'fuchsia', n: 'Fukszia', lat: 'Fuchsia', c: 'flower', a: 'flowering_shrub' },
  { k: 'lavatera', n: 'Mályva', lat: 'Lavatera', c: 'flower', a: 'annual_flower' },
  { k: 'cymbidium', n: 'Cimbídium orchidea', lat: 'Cymbidium', c: 'flower', a: 'orchid_arch' },
  { k: 'dendrobium', n: 'Dendrobium orchidea', lat: 'Dendrobium', c: 'flower', a: 'orchid_arch' },
  { k: 'cattleya', n: 'Cattleya orchidea', lat: 'Cattleya', c: 'flower', a: 'orchid_arch' },
  { k: 'oncidium', n: 'Oncidium orchidea', lat: 'Oncidium', c: 'flower', a: 'orchid_arch' },

  /* ───────── ZÖLDSÉGEK ───────── */
  { k: 'potato', n: 'Burgonya', lat: 'Solanum tuberosum', c: 'veg', a: 'root_veg', tox: 1 },
  { k: 'cabbage', n: 'Fejes káposzta', lat: 'Brassica oleracea', c: 'veg', a: 'brassica' },
  { k: 'cauliflower', n: 'Karfiol', lat: 'Brassica oleracea var. botrytis', c: 'veg', a: 'brassica' },
  { k: 'broccoli', n: 'Brokkoli', lat: 'Brassica oleracea var. italica', c: 'veg', a: 'brassica' },
  { k: 'kohlrabi', n: 'Karalábé', lat: 'Brassica oleracea var. gongylodes', c: 'veg', a: 'brassica' },
  { k: 'kale', n: 'Fodros kel', lat: 'Brassica oleracea var. sabellica', c: 'veg', a: 'brassica' },
  { k: 'brussels', n: 'Kelbimbó', lat: 'Brassica oleracea var. gemmifera', c: 'veg', a: 'brassica' },
  { k: 'pakchoi', n: 'Pak choi', lat: 'Brassica rapa subsp. chinensis', c: 'veg', a: 'brassica' },
  { k: 'beetroot', n: 'Cékla', lat: 'Beta vulgaris', c: 'veg', a: 'root_veg' },
  { k: 'turnip', n: 'Tarlórépa', lat: 'Brassica rapa', c: 'veg', a: 'root_veg' },
  { k: 'parsnip', n: 'Pasztinák', lat: 'Pastinaca sativa', c: 'veg', a: 'root_veg' },
  { k: 'celeriac', n: 'Gumós zeller', lat: 'Apium graveolens var. rapaceum', c: 'veg', a: 'root_veg' },
  { k: 'celery', n: 'Zeller (szár)', lat: 'Apium graveolens', c: 'veg', a: 'leafy_veg' },
  { k: 'sweetpotato', n: 'Batáta', lat: 'Ipomoea batatas', c: 'veg', a: 'root_veg' },
  { k: 'ginger', n: 'Gyömbér', lat: 'Zingiber officinale', c: 'veg', a: 'root_veg' },
  { k: 'horseradish', n: 'Torma', lat: 'Armoracia rusticana', c: 'veg', a: 'root_veg' },
  { k: 'leek', n: 'Póréhagyma', lat: 'Allium ampeloprasum', c: 'veg', a: 'leafy_veg' },
  { k: 'springonion', n: 'Újhagyma', lat: 'Allium fistulosum', c: 'veg', a: 'leafy_veg' },
  { k: 'peas', n: 'Borsó', lat: 'Pisum sativum', c: 'veg', a: 'legume_veg' },
  { k: 'broadbean', n: 'Lóbab', lat: 'Vicia faba', c: 'veg', a: 'legume_veg' },
  { k: 'runnerbean', n: 'Futóbab', lat: 'Phaseolus coccineus', c: 'veg', a: 'legume_veg' },
  { k: 'pumpkin', n: 'Sütőtök', lat: 'Cucurbita maxima', c: 'veg', a: 'fruiting_veg' },
  { k: 'squash', n: 'Tök', lat: 'Cucurbita pepo', c: 'veg', a: 'fruiting_veg' },
  { k: 'melon', n: 'Sárgadinnye', lat: 'Cucumis melo', c: 'veg', a: 'fruiting_veg' },
  { k: 'watermelon', n: 'Görögdinnye', lat: 'Citrullus lanatus', c: 'veg', a: 'fruiting_veg' },
  { k: 'corn', n: 'Csemegekukorica', lat: 'Zea mays', c: 'veg', a: 'fruiting_veg' },
  { k: 'okra', n: 'Bámia', lat: 'Abelmoschus esculentus', c: 'veg', a: 'fruiting_veg' },
  { k: 'artichoke', n: 'Articsóka', lat: 'Cynara scolymus', c: 'veg', a: 'fruiting_veg' },
  { k: 'asparagus_veg', n: 'Spárga', lat: 'Asparagus officinalis', c: 'veg', a: 'root_veg' },
  { k: 'rhubarb', n: 'Rebarbara', lat: 'Rheum rhabarbarum', c: 'veg', a: 'leafy_veg', tox: 1 },
  { k: 'chard', n: 'Mángold', lat: 'Beta vulgaris subsp. cicla', c: 'veg', a: 'leafy_veg' },
  { k: 'arugula', n: 'Rukkola', lat: 'Eruca sativa', c: 'veg', a: 'leafy_veg' },
  { k: 'endive', n: 'Endívia', lat: 'Cichorium endivia', c: 'veg', a: 'leafy_veg' },
  { k: 'fennel_veg', n: 'Édeskömény', lat: 'Foeniculum vulgare', c: 'veg', a: 'leafy_veg' },
  { k: 'sorrel', n: 'Sóska', lat: 'Rumex acetosa', c: 'veg', a: 'leafy_veg' },
  { k: 'mustardgreens', n: 'Mustárzöld', lat: 'Brassica juncea', c: 'veg', a: 'leafy_veg' },
  { k: 'watercress', n: 'Vízitorma', lat: 'Nasturtium officinale', c: 'veg', a: 'leafy_veg' },

  /* ───────── GYÜMÖLCSÖK ───────── */
  { k: 'apple', n: 'Alma', lat: 'Malus domestica', c: 'fruit', a: 'fruit_bush' },
  { k: 'pear', n: 'Körte', lat: 'Pyrus communis', c: 'fruit', a: 'fruit_bush' },
  { k: 'cherry', n: 'Cseresznye', lat: 'Prunus avium', c: 'fruit', a: 'fruit_bush' },
  { k: 'sourcherry', n: 'Meggy', lat: 'Prunus cerasus', c: 'fruit', a: 'fruit_bush' },
  { k: 'plum', n: 'Szilva', lat: 'Prunus domestica', c: 'fruit', a: 'fruit_bush' },
  { k: 'peach', n: 'Őszibarack', lat: 'Prunus persica', c: 'fruit', a: 'fruit_bush' },
  { k: 'apricot', n: 'Sárgabarack', lat: 'Prunus armeniaca', c: 'fruit', a: 'fruit_bush' },
  { k: 'blackberry', n: 'Szeder', lat: 'Rubus fruticosus', c: 'fruit', a: 'fruit_bush' },
  { k: 'currant', n: 'Ribizli', lat: 'Ribes rubrum', c: 'fruit', a: 'fruit_bush' },
  { k: 'gooseberry', n: 'Egres', lat: 'Ribes uva-crispa', c: 'fruit', a: 'fruit_bush' },
  { k: 'quince', n: 'Birs', lat: 'Cydonia oblonga', c: 'fruit', a: 'fruit_bush' },
  { k: 'elderberry', n: 'Fekete bodza', lat: 'Sambucus nigra', c: 'fruit', a: 'fruit_bush' },
  { k: 'walnut', n: 'Dió', lat: 'Juglans regia', c: 'fruit', a: 'ornamental_tree' },
  { k: 'hazelnut', n: 'Mogyoró', lat: 'Corylus avellana', c: 'fruit', a: 'fruit_bush' },
  { k: 'orange', n: 'Narancs', lat: 'Citrus sinensis', c: 'fruit', a: 'citrus_arch' },
  { k: 'mandarin', n: 'Mandarin', lat: 'Citrus reticulata', c: 'fruit', a: 'citrus_arch' },
  { k: 'lime_fruit', n: 'Lime', lat: 'Citrus aurantiifolia', c: 'fruit', a: 'citrus_arch' },
  { k: 'grapefruit', n: 'Grapefruit', lat: 'Citrus paradisi', c: 'fruit', a: 'citrus_arch' },
  { k: 'kiwi', n: 'Kivi', lat: 'Actinidia deliciosa', c: 'fruit', a: 'climber' },
  { k: 'pomegranate', n: 'Gránátalma', lat: 'Punica granatum', c: 'fruit', a: 'fruit_bush' },
  { k: 'avocado', n: 'Avokádó', lat: 'Persea americana', c: 'fruit', a: 'tropical_house' },

  /* ───────── DÍSZNÖVÉNYEK (cserjék, fák, fűfélék, kúszók) ───────── */
  { k: 'boxwood', n: 'Puszpáng', lat: 'Buxus sempervirens', c: 'orn', a: 'evergreen_shrub', tox: 1 },
  { k: 'thuja', n: 'Tuja', lat: 'Thuja occidentalis', c: 'orn', a: 'conifer', tox: 1 },
  { k: 'juniper', n: 'Boróka', lat: 'Juniperus', c: 'orn', a: 'conifer' },
  { k: 'spruce', n: 'Lucfenyő', lat: 'Picea abies', c: 'orn', a: 'conifer' },
  { k: 'pine', n: 'Erdeifenyő', lat: 'Pinus sylvestris', c: 'orn', a: 'conifer' },
  { k: 'yew', n: 'Tiszafa', lat: 'Taxus baccata', c: 'orn', a: 'conifer', tox: 1 },
  { k: 'holly', n: 'Magyal', lat: 'Ilex aquifolium', c: 'orn', a: 'evergreen_shrub', tox: 1 },
  { k: 'cherrylaurel', n: 'Babérmeggy', lat: 'Prunus laurocerasus', c: 'orn', a: 'evergreen_shrub', tox: 1 },
  { k: 'privet', n: 'Fagyal', lat: 'Ligustrum', c: 'orn', a: 'evergreen_shrub', tox: 1 },
  { k: 'photinia', n: 'Photinia', lat: 'Photinia × fraseri', c: 'orn', a: 'evergreen_shrub' },
  { k: 'euonymus', n: 'Kecskerágó', lat: 'Euonymus', c: 'orn', a: 'evergreen_shrub', tox: 1 },
  { k: 'pyracantha', n: 'Tűztövis', lat: 'Pyracantha', c: 'orn', a: 'evergreen_shrub' },
  { k: 'cotoneaster', n: 'Madárbirs', lat: 'Cotoneaster', c: 'orn', a: 'evergreen_shrub' },
  { k: 'mahonia', n: 'Mahónia', lat: 'Mahonia aquifolium', c: 'orn', a: 'evergreen_shrub' },
  { k: 'aucuba', n: 'Aukuba', lat: 'Aucuba japonica', c: 'orn', a: 'evergreen_shrub' },
  { k: 'nandina', n: 'Szent bambusz', lat: 'Nandina domestica', c: 'orn', a: 'evergreen_shrub' },
  { k: 'santolina', n: 'Cipruska', lat: 'Santolina', c: 'orn', a: 'evergreen_shrub' },
  { k: 'heather', n: 'Hanga', lat: 'Calluna vulgaris', c: 'orn', a: 'evergreen_shrub' },
  { k: 'berberis', n: 'Borbolya', lat: 'Berberis', c: 'orn', a: 'flowering_shrub' },
  { k: 'forsythia', n: 'Aranyeső', lat: 'Forsythia', c: 'orn', a: 'flowering_shrub' },
  { k: 'lilac', n: 'Orgona', lat: 'Syringa vulgaris', c: 'orn', a: 'flowering_shrub' },
  { k: 'weigela', n: 'Rózsalonc', lat: 'Weigela', c: 'orn', a: 'flowering_shrub' },
  { k: 'spiraea', n: 'Gyöngyvessző', lat: 'Spiraea', c: 'orn', a: 'flowering_shrub' },
  { k: 'deutzia', n: 'Gyöngyvirágcserje', lat: 'Deutzia', c: 'orn', a: 'flowering_shrub' },
  { k: 'philadelphus', n: 'Jezsámen', lat: 'Philadelphus', c: 'orn', a: 'flowering_shrub' },
  { k: 'viburnum', n: 'Bangita', lat: 'Viburnum', c: 'orn', a: 'flowering_shrub' },
  { k: 'hibiscus_syriacus', n: 'Mályvacserje', lat: 'Hibiscus syriacus', c: 'orn', a: 'flowering_shrub' },
  { k: 'buddleia', n: 'Nyáriorgona', lat: 'Buddleja davidii', c: 'orn', a: 'flowering_shrub' },
  { k: 'oleander', n: 'Leander', lat: 'Nerium oleander', c: 'orn', a: 'flowering_shrub', tox: 1, diff: 'med' },
  { k: 'rhododendron', n: 'Rododendron', lat: 'Rhododendron', c: 'orn', a: 'flowering_shrub', tox: 1 },
  { k: 'azalea', n: 'Azálea', lat: 'Rhododendron simsii', c: 'orn', a: 'flowering_shrub', tox: 1 },
  { k: 'camellia', n: 'Kamélia', lat: 'Camellia japonica', c: 'orn', a: 'flowering_shrub' },
  { k: 'gardenia', n: 'Gardénia', lat: 'Gardenia jasminoides', c: 'orn', a: 'flowering_shrub', diff: 'hard', hum: 'high' },
  { k: 'hawthorn', n: 'Galagonya', lat: 'Crataegus', c: 'orn', a: 'flowering_shrub' },
  { k: 'dogwood', n: 'Som', lat: 'Cornus', c: 'orn', a: 'flowering_shrub' },
  { k: 'skimmia', n: 'Skimmia', lat: 'Skimmia japonica', c: 'orn', a: 'evergreen_shrub' },
  { k: 'japanesemaple', n: 'Japán juhar', lat: 'Acer palmatum', c: 'orn', a: 'ornamental_tree' },
  { k: 'birch', n: 'Nyír', lat: 'Betula pendula', c: 'orn', a: 'ornamental_tree' },
  { k: 'ginkgo', n: 'Ginkgo', lat: 'Ginkgo biloba', c: 'orn', a: 'ornamental_tree' },
  { k: 'magnolia', n: 'Liliomfa', lat: 'Magnolia', c: 'orn', a: 'ornamental_tree' },
  { k: 'willow', n: 'Szomorúfűz', lat: 'Salix babylonica', c: 'orn', a: 'ornamental_tree' },
  { k: 'maple', n: 'Juhar', lat: 'Acer', c: 'orn', a: 'ornamental_tree' },
  { k: 'linden', n: 'Hárs', lat: 'Tilia', c: 'orn', a: 'ornamental_tree' },
  { k: 'hornbeam', n: 'Gyertyán', lat: 'Carpinus betulus', c: 'orn', a: 'ornamental_tree' },
  { k: 'catalpa', n: 'Szivarfa', lat: 'Catalpa', c: 'orn', a: 'ornamental_tree' },
  { k: 'wisteria', n: 'Lilaakác', lat: 'Wisteria', c: 'orn', a: 'climber', tox: 1 },
  { k: 'clematis', n: 'Iszalag', lat: 'Clematis', c: 'orn', a: 'climber', tox: 1 },
  { k: 'honeysuckle', n: 'Lonc', lat: 'Lonicera', c: 'orn', a: 'climber' },
  { k: 'bougainvillea', n: 'Murvafürt', lat: 'Bougainvillea', c: 'orn', a: 'climber' },
  { k: 'virginiacreeper', n: 'Vadszőlő', lat: 'Parthenocissus', c: 'orn', a: 'climber' },
  { k: 'trumpetvine', n: 'Trombitafolyondár', lat: 'Campsis radicans', c: 'orn', a: 'climber' },
  { k: 'jasmine', n: 'Jázmin', lat: 'Jasminum', c: 'orn', a: 'climber' },
  { k: 'starjasmine', n: 'Csillagjázmin', lat: 'Trachelospermum jasminoides', c: 'orn', a: 'climber' },
  { k: 'bamboo', n: 'Bambusz', lat: 'Phyllostachys', c: 'orn', a: 'ornamental_grass' },
  { k: 'pampasgrass', n: 'Pampafű', lat: 'Cortaderia selloana', c: 'orn', a: 'ornamental_grass' },
  { k: 'miscanthus', n: 'Kínai nád', lat: 'Miscanthus sinensis', c: 'orn', a: 'ornamental_grass' },
  { k: 'fountaingrass', n: 'Tollborzfű', lat: 'Pennisetum', c: 'orn', a: 'ornamental_grass' },
  { k: 'festuca', n: 'Kék csenkesz', lat: 'Festuca glauca', c: 'orn', a: 'ornamental_grass' },
  { k: 'carex', n: 'Sás', lat: 'Carex', c: 'orn', a: 'ornamental_grass' },
  { k: 'hosta', n: 'Árnyékliliom', lat: 'Hosta', c: 'orn', a: 'perennial_flower', light: 'low' },
  { k: 'heuchera', n: 'Tűzgyöngyajak', lat: 'Heuchera', c: 'orn', a: 'perennial_flower' },
  { k: 'bergenia', n: 'Bőrlevél', lat: 'Bergenia', c: 'orn', a: 'perennial_flower' },
  { k: 'astilbe', n: 'Tollbuga', lat: 'Astilbe', c: 'orn', a: 'perennial_flower', light: 'medium' },
  { k: 'lavender_orn', n: 'Levendula (sövény)', lat: 'Lavandula', c: 'orn', a: 'evergreen_shrub' },
  { k: 'ornamentalcabbage', n: 'Dísz káposzta', lat: 'Brassica oleracea (dísz)', c: 'orn', a: 'brassica' },

  /* ───────── TOVÁBBI SZOBANÖVÉNYEK ───────── */
  { k: 'coleus', n: 'Tarkacsalán', lat: 'Coleus scutellarioides', c: 'house', a: 'foliage_house' },
  { k: 'alocasia', n: 'Elefántfül', lat: 'Alocasia', c: 'house', a: 'tropical_house', tox: 1 },
  { k: 'colocasia', n: 'Kolokázia', lat: 'Colocasia', c: 'house', a: 'tropical_house', tox: 1 },
  { k: 'caladium', n: 'Kaládium', lat: 'Caladium', c: 'house', a: 'tropical_house', tox: 1 },
  { k: 'oxalis', n: 'Lila madársóska', lat: 'Oxalis triangularis', c: 'house', a: 'foliage_house', tox: 1 },
  { k: 'aspidistra', n: 'Vasfű', lat: 'Aspidistra elatior', c: 'house', a: 'foliage_house', light: 'low' },
  { k: 'clivia', n: 'Klívia', lat: 'Clivia miniata', c: 'house', a: 'foliage_house', tox: 1 },
  { k: 'bromeliad', n: 'Bromélia', lat: 'Guzmania', c: 'house', a: 'tropical_house' },
  { k: 'tillandsia', n: 'Légnövény', lat: 'Tillandsia', c: 'house', a: 'tropical_house', tip: 'Föld nélkül él; hetente áztasd be 20–30 percre, majd csöpögtesd le jól.' },
  { k: 'hypoestes', n: 'Pöttyös levél', lat: 'Hypoestes phyllostachya', c: 'house', a: 'tropical_house' },
  { k: 'pachira', n: 'Pachira (pénzfa)', lat: 'Pachira aquatica', c: 'house', a: 'foliage_house' },
  { k: 'dracaena_fragrans', n: 'Kukoricapálma', lat: 'Dracaena fragrans', c: 'house', a: 'foliage_house', tox: 1 },
  { k: 'cordyline', n: 'Cordyline', lat: 'Cordyline fruticosa', c: 'house', a: 'foliage_house', tox: 1 },
  { k: 'philodendron_selloum', n: 'Filodendron Selloum', lat: 'Philodendron bipinnatifidum', c: 'house', a: 'tropical_house', tox: 1 },
  { k: 'rhaphidophora', n: 'Minimonstera', lat: 'Rhaphidophora tetrasperma', c: 'house', a: 'tropical_house', tox: 1 },
  { k: 'stromanthe', n: 'Stromanthe', lat: 'Stromanthe sanguinea', c: 'house', a: 'tropical_house' },
  { k: 'ctenanthe', n: 'Ctenanthe', lat: 'Ctenanthe', c: 'house', a: 'tropical_house' },
  { k: 'ceropegia', n: 'Szívfüzér', lat: 'Ceropegia woodii', c: 'house', a: 'succulent_arch' },

  /* ───────── TOVÁBBI PÁLMÁK ───────── */
  { k: 'trachycarpus', n: 'Kínai kenderpálma', lat: 'Trachycarpus fortunei', c: 'palm', a: 'palm_arch' },
  { k: 'phoenix', n: 'Datolyapálma', lat: 'Phoenix', c: 'palm', a: 'palm_arch' },
  { k: 'washingtonia', n: 'Washingtonia pálma', lat: 'Washingtonia', c: 'palm', a: 'palm_arch' },
  { k: 'livistona', n: 'Livistona pálma', lat: 'Livistona', c: 'palm', a: 'palm_arch' },

  /* ───────── TOVÁBBI FŰSZEREK ───────── */
  { k: 'tarragon', n: 'Tárkony', lat: 'Artemisia dracunculus', c: 'herb', a: 'herb_arch' },
  { k: 'marjoram', n: 'Majoránna', lat: 'Origanum majorana', c: 'herb', a: 'herb_arch' },
  { k: 'savory', n: 'Borsfű', lat: 'Satureja', c: 'herb', a: 'herb_arch' },
  { k: 'lovage', n: 'Lestyán', lat: 'Levisticum officinale', c: 'herb', a: 'herb_arch' },
  { k: 'baylaurel', n: 'Babér', lat: 'Laurus nobilis', c: 'herb', a: 'evergreen_shrub' },
  { k: 'lemongrass', n: 'Citromfű (pázsit)', lat: 'Cymbopogon citratus', c: 'herb', a: 'herb_arch' },
  { k: 'catnip', n: 'Macskamenta', lat: 'Nepeta cataria', c: 'herb', a: 'herb_arch' },

  /* ───────── TOVÁBBI POZSGÁSOK / KAKTUSZOK ───────── */
  { k: 'agave', n: 'Agávé', lat: 'Agave', c: 'succ', a: 'succulent_arch', tox: 1 },
  { k: 'gasteria', n: 'Gasteria', lat: 'Gasteria', c: 'succ', a: 'succulent_arch' },
  { k: 'aeonium', n: 'Aeonium', lat: 'Aeonium', c: 'succ', a: 'succulent_arch' },
  { k: 'portulacaria', n: 'Elefántbokor', lat: 'Portulacaria afra', c: 'succ', a: 'succulent_arch' },
  { k: 'graptopetalum', n: 'Graptopetalum', lat: 'Graptopetalum', c: 'succ', a: 'succulent_arch' },
  { k: 'echinocactus', n: 'Aranygömb kaktusz', lat: 'Echinocactus grusonii', c: 'succ', a: 'cactus_arch' },
  { k: 'cereus', n: 'Cereus', lat: 'Cereus', c: 'succ', a: 'cactus_arch' },
  { k: 'rebutia', n: 'Rebutia', lat: 'Rebutia', c: 'succ', a: 'cactus_arch' },
  { k: 'astrophytum', n: 'Püspöksüveg kaktusz', lat: 'Astrophytum', c: 'succ', a: 'cactus_arch' },
  { k: 'ferocactus', n: 'Ferocactus', lat: 'Ferocactus', c: 'succ', a: 'cactus_arch' },
  { k: 'epiphyllum', n: 'Levélkaktusz', lat: 'Epiphyllum', c: 'succ', a: 'succulent_arch', hum: 'med' }
];
